"""Optimization utilities."""

from .exceptions import (
    BacktrackingLineSearchError,
    CenteringStepError,
    ConstraintBoundaryError,
    InteriorPointMethodError,
    InvalidDescentDirectionError,
    NewtonStepError,
    OptimizationError,
    ProblemInfeasibleError,
    SevereCurvatureError,
)
from .numerical_helpers import (
    solve_arrow_sparsity_pattern,
    solve_block_plus_one,
    solve_diagonal,
    solve_diagonal_eta_inverse,
    solve_kkt_system,
    solve_rank_one_update,
    solve_rank_p_update,
    solve_with_schur,
)
from .optimization import (
    EqualityConstrainedInteriorPointMethodSolver,
    InteriorPointMethodResult,
    InteriorPointMethodSolver,
    NewtonResult,
    OptimizationResult,
    OptimizationSettings,
    Optimizer,
    PhaseIInteriorPointSolver,
    PhaseISolver,
    ProblemCertifiablyInfeasibleError,
    ProblemMarginallyFeasibleError,
)

__all__ = [
    "BacktrackingLineSearchError",
    "CenteringStepError",
    "ConstraintBoundaryError",
    "EqualityConstrainedInteriorPointMethodSolver",
    "InteriorPointMethodError",
    "InteriorPointMethodResult",
    "InteriorPointMethodSolver",
    "InvalidDescentDirectionError",
    "NewtonResult",
    "NewtonStepError",
    "OptimizationError",
    "OptimizationResult",
    "OptimizationSettings",
    "Optimizer",
    "PhaseIInteriorPointSolver",
    "PhaseISolver",
    "ProblemCertifiablyInfeasibleError",
    "ProblemInfeasibleError",
    "ProblemMarginallyFeasibleError",
    "SevereCurvatureError",
    "solve_arrow_sparsity_pattern",
    "solve_block_plus_one",
    "solve_diagonal",
    "solve_diagonal_eta_inverse",
    "solve_kkt_system",
    "solve_rank_one_update",
    "solve_rank_p_update",
    "solve_with_schur",
]
